version: '3.9'

services:
    postgres:
        image: postgres:latest
        container_name: e-commerce_database
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: adminpassword
            POSTGRES_DB: e-commerce
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
